export const STORAGE_KEY = {
  SYSTEM_CONFIG: {
    SERVER_URL: 'CREATUS_SECURITY_SYSTEM_CONFIG_SERVER_URL',
    THEME: 'CREATUS_SECURITY_SYSTEM_CONFIG_THEME',
    LANGUAGE: 'CREATUS_SECURITY_SYSTEM_CONFIG_LANGUAGE'
  }
} as const
